openapi: 3.0.1
info:
  title: CompositeAPI
  description: API Definition of CompositeAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/contacts
paths:
  /greet/{name}:
    get:
      parameters:
      - name: name
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
