openapi: 3.0.1
info:
  title: composite
  description: API Definition of composite
  version: 1.0.0
servers:
- url: http://localhost:8290/composite
paths:
  /greeting:
    get:
      responses:
        default:
          description: Default response
  /greeting/{name}:
    get:
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /customer/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
